<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>54c070f5-6756-46c0-a89b-c5de6753b8f7</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[data-id='\31 69'] .btn</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'btn btn-to-cart products__to-cart-btn')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn-to-cart products__to-cart-btn</value>
        <webElementGuid>93b5113e-81f5-44b1-9157-73c0e85a8d44</webElementGuid>
    </webElementProperties>
</WebElementEntity>