<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>71f3f63b-a57b-4cd9-90f4-fdfc9efb2e1b</elementGuidId>
    <imagePath></imagePath>
    <name>input_props_152158__1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/main[1]/div[1]/div[1]/div[1]/form[1]/div[6]/div[1]/div[3]/input[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'props[152158][]')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>props[152158][]</value>
        <webElementGuid>959272c6-49fc-4930-8e89-3899391ce1b3</webElementGuid>
    </webElementProperties>
</WebElementEntity>